name: adaptive_student_time
  
description: A student productivity app.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  

  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  supabase_flutter: ^2.12.0
  intl: ^0.19.0
  
  table_calendar: ^3.1.0
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  google_mlkit_digital_ink_recognition: ^0.13.0
  excel: ^4.0.6
  file_picker: ^10.3.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
